name = "LIMPSBridge"
uuid = "a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6"
authors = ["CCL + WaveCaster Team"]
version = "0.2.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6cf"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
HTTP = "1.5"
JSON3 = "1.12"
julia = "1.6"
